### ISSUE TITLE
anket sonucu

### ISSUE THREAD

**Issue by wahshibinharb** [hyPerdarKness/Poll-Anket#1]
Hocam elinize saglik. Bir kaç önerim olacak eğer güncelleme yapmanız mümkünse daha kullanılır olabilir.

- Anket sonucu gizlenip gösterilebilir hale getirilebilir mi? Ek olarak Admin panelinden görüntülenebilir mi
- Bir anket içerisinde birden fazla soru sorabilir miyiz? 
- Tüm IP temizlemek yerine ip görüp tek tek silebilsek daha iyi olur.. herseyi sifirliyor..
- Anket Resim Eklense daha iyi olur. Görsel Anketi vb.
- Kullanıcı Şifre ile ankete katılsa çok daha klas olur. 

Tekrardan emeginize saglik.

**Comment by hyPerdarKness** [comment]
merhaba,

bir sonraki güncelleme de bazı eklemeler yapılacaktır.

bildirim için teşekkürler.
